# Generated by Django 4.2.15 on 2024-10-22 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grandpaapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='workout',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='grandpaapi.workout'),
            preserve_default=False,
        ),
    ]
