# Generated by Django 4.2.15 on 2024-10-23 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grandpaapi', '0002_log_workout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='img_source',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='picture',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='grandpaapi.post'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='upload_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL),
        ),
    ]
